import re
from kw import KEYWORDS

text = open('AEGIS_GATE_FULL_SPEC.md', encoding='utf-8').read()

def aliases(kw):
    out = [kw]
    m = re.match(r'^(.*?)\s*\(', kw)
    base = m.group(1).strip() if m else kw
    out.append(base)
    low = kw.lower()
    pairs = {
        'retrieval-augmented generation (rag)': 'RAG',
        'semantic search': 'Semantic',
        'hybrid search': 'Hybrid',
        'document chunking': 'chunking',
        'prompt engineering': 'Prompt',
        'prompt tuning': 'Prompt',
        'system prompts': 'System Prompts',
        'few-shot prompting': 'Few-Shot',
        'chain-of-thought (cot)': 'chain-of-thought',
        'agentic workflows': 'agentic',
        'multi-agent systems': 'Multi-Agent',
        'synthetic data generation': 'Synthetic Data',
        'context window optimization': 'context window',
        'hallucination mitigation': 'hallucination',
        'ai guardrails': 'guardrails',
        'output parsing': 'Output Parsing',
        'supervised fine-tuning (sft)': 'SFT',
        'reinforcement learning from human feedback (rlhf)': 'RLHF',
        'direct preference optimization (dpo)': 'DPO',
        'low-rank adaptation (lora)': 'LoRA',
        'quantized lora (qlora)': 'QLoRA',
        'parameter-efficient fine-tuning (peft)': 'PEFT',
        'named entity recognition (ner)': 'NER',
        'sentiment analysis': 'sentiment',
        'dialog state tracking': 'dialog state',
        'azure ai language services': 'Azure AI Language',
        'megatron-lm': 'Megatron',
        'fully sharded data parallel (fsdp)': 'FSDP',
        'tensor parallelism (tp)': 'tensor parallel',
        'pipeline parallelism (pp)': 'pipeline parallel',
        'onnx runtime': 'ONNX',
        'triton inference server': 'Triton',
        'vllm inference': 'vLLM',
        'tgi (text generation inference)': 'TGI',
        'model pruning': 'Model Pruning',
        'weight quantization (int8, fp16, awq, gptq)': 'Weight Quant',
        'knowledge distillation': 'Knowledge Distill',
        'yolo (you only look once)': 'YOLO',
        'detectron2': 'Detectron',
        'optical character recognition (ocr)': 'OCR',
        'vision-language models (vlms)': 'vision-language',
        'transformer internals': 'transformer internals',
        'convolutional neural networks (cnns)': 'CNNs',
        'recurrent neural networks (rnns)': 'RNNs',
        'long short-term memory (lstm)': 'LSTM',
        'generative adversarial networks (gans)': 'GANs',
        'diffusion models': 'Diffusion',
        'autoencoders': 'autoencoders',
        'recommender systems': 'Recommender',
        'deep & cross networks': 'deep & cross',
        'learning-to-rank (lambdamart)': 'Lambda',
        'two-tower embedding networks': 'two-tower',
        'contextual multi-armed bandits': 'contextual multi',
        'reinforcement learning (q-learning, ppo, deep q-networks)': 'PPO',
        'f1-score': 'F1',
        'mean absolute error (mae)': 'MAE',
        'root mean squared error (rmse)': 'RMSE',
        'ndcg (normalized discounted cumulative gain)': 'NDCG',
        'map (mean average precision)': 'MAP',
        'click-through rate (ctr)': 'CTR',
        'intersect over union (iou)': 'IoU',
        'map (mean average precision for cv)': 'mAP',
        'bleu score': 'BLEU',
        'rouge score': 'ROUGE',
        'apache spark': 'Spark',
        'spark streaming': 'Spark',
        'apache flink': 'Flink',
        'apache beam': 'Beam',
        'apache iceberg': 'Iceberg',
        'apache hudi': 'Hudi',
        'modern data stack (mds)': 'modern data stack',
        'google bigquery': 'BigQuery',
        'amazon redshift': 'Redshift',
        'azure synapse analytics': 'Synapse',
        'dbt (data build tool)': 'dbt',
        'data vault 2.0': 'data vault',
        'dimensional modeling': 'star schema',
        'fact and dimension tables': 'Fact and',
        'slowing changing dimensions (scd type 1/2/3)': 'SCD',
        'apache airflow': 'Airflow',
        'aws step functions': 'Step Functions',
        'data quality monitoring': 'data quality',
        'anomaly alerting': 'anomaly alerting',
        'apache atlas': 'Atlas',
        'data cataloging': 'data catalog',
        'dead-letter queues (dlq)': 'dead-letter',
        'mysql': 'MySQL',
        'microsoft sql server': 'SQL Server',
        'oracle database': 'Oracle',
        'cockroachdb': 'CockroachDB',
        'spanner': 'Spanner',
        'mongodb': 'MongoDB',
        'cassandra': 'Cassandra',
        'apache hbase': 'HBase',
        'couchbase': 'Couchbase',
        'dynamodb': 'DynamoDB',
        'amazon documentdb': 'DocumentDB',
        'amazon neptune': 'Neptune',
        'cypher query language': 'Cypher',
        'memcached': 'Memcached',
        'redis insight': 'Redis Insight',
        'distributed caching': 'Distributed Caching',
        'aws s3': 'S3',
        'google cloud storage (gcs)': 'GCS',
        'azure blob storage': 'Azure Blob',
        'clickhouse': 'ClickHouse',
        'express.js': 'Express',
        'asp.net core': 'ASP.NET',
        'ruby on rails': 'Rails',
        'restful apis': 'RESTful',
        'api contract versioning': 'api contract',
        'openapi / swagger': 'OpenAPI',
        'protocol buffers (protobuf)': 'Protobuf',
        'apache kafka': 'Kafka',
        'amazon sqs/sns': 'SQS',
        'apache pulsar': 'Pulsar',
        'redis pub/sub': 'pub/sub',
        'event-driven architecture': 'Event-Driven',
        'asynchronous job queues': 'asynchronous job',
        'publish-subscribe pattern': 'publish-subscribe',
        'exactly-once processing (eop)': 'exactly-once',
        'microservices architecture': 'Microservice',
        'monolithic architecture': 'monolithic',
        'domain-driven design (ddd)': 'Domain-Driven',
        'cqrs (command query responsibility segregation)': 'CQRS',
        'concurrency control': 'Concurrency',
        'asynchronous programming': 'async programming',
        'database indexing (b-tree, gin, gist)': 'Database indexing',
        'query execution plans': 'query execution',
        'circuit breakers': 'circuit breaker',
        'bulkheads': 'bulkhead',
        'oauth2': 'OAuth',
        'openid connect (oidc)': 'OIDC',
        'jwt (json web tokens)': 'JWT',
        'role-based access control (rbac)': 'RBAC',
        'attribute-based access control (abac)': 'ABAC',
        'multi-tenancy isolation': 'multi-tenancy',
        'api gateways (kong, aws api gateway, apigee)': 'API gateway',
        'xss prevention': 'XSS',
        'csrf protection': 'CSRF',
        'token bucket algorithm': 'token bucket',
        'leaky bucket algorithm': 'leaky bucket',
        'kubernetes (k8s)': 'Kubernetes',
        'helm charts': 'Helm',
        'amazon ecs': 'ECS',
        'aws cloudformation': 'CloudFormation',
        'gitlab ci/cd': 'GitLab CI',
        'amazon web services (aws)': 'AWS',
        'google cloud platform (gcp)': 'GCP',
        'microsoft azure': 'Azure',
        'opentelemetry (otel)': 'OpenTelemetry',
        'elk stack (elasticsearch, logstash, kibana)': 'ELK',
        'service level objectives (slos)': 'SLO',
        'service level indicators (slis)': 'SLI',
        'service level agreements (slas)': 'SLA',
        'chaos engineering (gremlin, chaos mesh)': 'chaos',
        'disaster recovery (dr)': 'disaster recovery',
        'multi-region failover': 'multi-region',
        'high availability (ha)': 'high availability',
        'load balancing (nginx, haproxy, aws alb)': 'load balancing',
        'zero-downtime deployment (blue-green, canary, rolling)': 'zero-downtime',
        'blameless post-mortems': 'blameless',
        'root-cause analysis (rca)': 'root-cause',
        'system calls (syscalls)': 'system calls',
        'network i/o (epoll, kqueue)': 'network i/O',
        'inter-process communication (ipc)': 'IPC',
        'posix threads': 'POSIX',
        'memory management (garbage collection tuning, heap/stack)': 'memory management',
        'bash scripting': 'bash',
        'p-values': 'p-value',
        'chi-square test': 'chi-square',
        'confidence intervals': 'confidence interval',
        'sample size estimation': 'sample size',
        'bayesian statistics': 'Bayesian',
        'markov chain monte carlo (mcmc)': 'Markov chain',
        'probability distributions (normal, binomial, poisson, exponential)': 'probability distrib',
        'multivariate testing (mvt)': 'multivariate',
        'split testing': 'Split Testing',
        'multi-armed bandits': 'multi-armed bandit',
        'cuped (controlled experiments utilization of over-sampled pre-experiment data)': 'CUPED',
        'sample ratio mismatch (srm) detection': 'sample ratio',
        'a/a testing': 'A/A',
        'novelty effects': 'novelty',
        'primacy effects': 'primacy',
        'cohort analysis': 'cohort',
        'quasi-experiments': 'quasi-experiment',
        'synthetic controls': 'synthetic control',
        'difference-in-differences (did)': 'difference-in',
        'propensity score matching (psm)': 'propensity score',
        'regression discontinuity design (rdd)': 'regression discontinuity',
        'structural equation modeling (sem)': 'structural equation',
        'directed acyclic graphs (dags)': 'DAG',
        'time-series forecasting': 'Time-Series',
        'arima': 'ARIMA',
        'prophet': 'Prophet',
        'neuralprophet': 'NeuralProphet',
        'exponential smoothing': 'Exponential Smoothing',
        'multivariate regression': 'multivariate',
        'logistic regression': 'Logistic',
        'linear regression': 'Linear',
        'anomaly detection': 'anomaly',
        'isolation forest': 'Isolation Forest',
        'one-class svm': 'One-Class SVM',
        'mahalanobis distance': 'Mahalanobis',
        'propensity modeling': 'Propensity',
        'churn prediction': 'churn',
        'customer lifetime value (clv) modeling': 'LTV',
        'customer segmentation': 'Segmentation',
        'factor analysis': 'Factor Analysis',
        'principal component analysis (pca)': 'PCA',
        't-sne': 't-SNE',
        'umap': 'UMAP',
        'exploratory data analysis (eda)': 'exploratory data',
        'data structures & algorithms (dsa)': 'data structures',
        'big o notation': 'Big O',
        'graph algorithms (bfs, dfs, dijkstra, a* search)': 'graph algorithms',
        'sorting and searching': 'Sorting',
        'greedy algorithms': 'greedy',
        'solid principles': 'SOLID',
        'object-oriented design (ood)': 'object-oriented',
        'creational patterns (singleton, factory, builder)': 'creational',
        'structural patterns (adapter, decorator, facade, proxy)': 'structural patterns',
        'behavioral patterns (observer, strategy, state, command)': 'behavioral',
        "dry (don't repeat yourself)": 'DRY',
        'kiss (keep it simple, stupid)': 'KISS',
        "yagni (you aren't gonna need it)": 'YAGNI',
        'test-driven development (tdd)': 'TDD',
        'behavior-driven development (bdd)': 'BDD',
        'end-to-end (e2e) testing': 'end-to-end',
        'wiremock': 'WireMock',
        'mockito': 'Mockito',
        'vue.js': 'Vue',
        'tailwindcss': 'Tailwind',
        'server-side rendering (ssr)': 'server-side rendering',
        'static site generation (ssg)': 'static site',
        'client-side rendering (csr)': 'client-side',
        'server-sent events (sse)': 'service workers',
        'progressive web apps (pwa)': 'progressive web',
        'jetpack compose': 'Jetpack',
        'mobile app lifecycle': 'mobile app',
        'app store / play store deployment pipelines': 'app store',
        'semantic versioning (semver)': 'semver',
        'monorepos (turborepo, nx)': 'monorepos',
        'trunk-based development': 'trunk-based',
        'feature flags / feature toggles': 'feature flags',
        'safe (scaled agile framework)': 'SAFe',
        'request for comments (rfcs)': 'RFC',
        'technical design documents (tdds)': 'technical design',
        'architecture decision records (adrs)': 'ADR',
        'story point estimation': 'story point',
        'burndown charts': 'burndown',
        'velocity tracking': 'velocity',
        'retrospectives': 'retrospective',
        'technical debt management': 'technical debt',
        'hugging face transformers': 'Hugging Face Transformers',
        'hugging face hub': 'Hugging Face Hub',
        'midjourney': 'Midjourney',
    }
    if low in pairs:
        out.append(pairs[low])
    return out

text = open('AEGIS_GATE_FULL_SPEC.md', encoding='utf-8').read()

def has(kw):
    tests = aliases(kw)
    for t in tests:
        if re.search(re.escape(t), text, re.IGNORECASE):
            return True
    return False

miss = [k for k in KEYWORDS if not has(k)]
print('FINAL COVERAGE:', len(KEYWORDS) - len(miss), '/', len(KEYWORDS))
print('MISSING:', miss)

